export const SET_SPINNER_VISIBLE = 'SET_SPINNER_VISIBLE';

export const SET_ALERT_BOX_VISIBILITY = 'SET_ALERT_BOX_VISIBILITY';

export const SET_SPOTS_NEAR_USER = 'SET_SPOTS_NEAR_USER';
export const GET_SPOTS_NEAR_USER = 'GET_SPOTS_NEAR_USER';

export const SET_SPOTS_AVAILABILITY = 'SET_SPOTS_AVAILABILITY';

export const SET_SELECTED_SPOT = 'SET_SELECTED_SPOT';
