const colors = {
  PRIMARY_COLOR: '#003366',
  SECONDARY_COLOR: '#66A3D2',
  ACCENT_COLOR: '#FFA500',
  BACKGROUND_COLOR: '#F5F5F5',
  TEXT_COLOR_ON_LIGHT_BACKGROUND: '#333333',
  TEXT_COLOR_ON_DARK_BACKGROUND: '##FFFFFF',
};
export {colors};
